repos:
    - repo: https://github.com/timothycrosley/isort
      rev: 4.3.21
      hooks:
      - id: isort
        exclude: ^alembic/
        additional_dependencies: ["toml"]
        language_version: python3.8
    - repo: https://github.com/psf/black
      rev: stable
      hooks:
      - id: black
        exclude: ^alembic/
        language_version: python3.8